#Update all the sections by editing the data.yml file inside _data folder.

<<<<<<< HEAD
baseurl: '' #change it according to your repository name
=======
# Site Settings
title: My Resume
url: 'http://webjeda.com'
>>>>>>> 9fb69e1def08f55dabd380022f0f5c4d3bbcb6b4

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
<<<<<<< HEAD
theme_skin: orange
# blue turquoise green berry orange ceramic

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True
=======
theme_skin: orange # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
>>>>>>> 9fb69e1def08f55dabd380022f0f5c4d3bbcb6b4

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
<<<<<<< HEAD
theme: jekyll-theme-cayman
=======
>>>>>>> 9fb69e1def08f55dabd380022f0f5c4d3bbcb6b4
